spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/communitydb
    driver-class-name: org.postgresql.Driver
    username: comm
    password: comm
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
